/**********************************************************
 * File: EnterpriseManagement.java
 * Purpose: Main menu of the program.
 *********************************************************/

package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Client;
import model.Supplier;
import model.Employee;
import model.Product;
import javax.swing.*;

import org.apache.log4j.Logger;

public class EnterpriseManagement extends javax.swing.JFrame
{
    private JButton jButton_Contact; // Shows the Contact's Main Button on the Enterprise Management's Main Menu
    private JButton jButton_Despesas; // Shows the Expense's Main Button on the Enterprise Management's Main Menu
    private JButton jButton_Estoque; // Shows the Stock's Main Button on the Enterprise Management's Main Menu
    private JButton jButton_HistoricoCompraVenda; // Shows the Buying Selling Historic's Main Button on the Enterprise Management's Main Menu
    private JButton jButton_VendaCompra; // Shows the Selling Buying's Main Button on the Enterprise Management Main's Menu
    private JLabel jLabel1; // Shows the "Enterprise Management - 1.0" sentence on the Main Menu 
    private JPanel jPanel1; // Shows the entire "Enterprise Management" Screen Layout
    
    Client objectClient; // Instantiates objectClient
    Employee objectEmployee; // Instantiates an object Employee
    Supplier objectSupplier; // Instantiates an object Supplier
    Product objectProduct; // Instantiates an object Product
    ArrayList<Product> productList; // Instantiates a product List
    static Logger log = Logger.getLogger(EnterpriseManagement.class.getName());

    // Constructor of the EnterpriseManagement's class
    public EnterpriseManagement()
    {
        initComponents();
        objectProduct = new Product("Produto", null, 10.0, WIDTH, 0);
        productList = new ArrayList<Product>();
        productList.add(objectProduct);
        objectClient = new Client("Cliente", null, null, null);
        objectEmployee = new Employee("Funcionario", null, null, null, null, null, WIDTH, null);
        objectSupplier = new Supplier("Fornecedor", null, null, null, null);
        
        log.debug("Load EnterpriseManagement");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Contact = new javax.swing.JButton();
        jButton_Estoque = new javax.swing.JButton();
        jButton_VendaCompra = new javax.swing.JButton();
        jButton_Despesas = new javax.swing.JButton();
        jButton_HistoricoCompraVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 800));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Gestão Empresa - 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton_Contact.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_Contact.setText("Contatos");
        jButton_Contact.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_ContatosActionPerformed(evt);
            }
        });

        jButton_Estoque.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_Estoque.setText("Estoque");
        jButton_Estoque.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_EstoqueActionPerformed(evt);
            }
        });

        jButton_VendaCompra.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_VendaCompra.setText("Venda/Compra");
        jButton_VendaCompra.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_VendaCompraActionPerformed(evt);
            }
        });

        jButton_Despesas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_Despesas.setText("Despesas");
        jButton_Despesas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_DespesasActionPerformed(evt);
            }
        });

        jButton_HistoricoCompraVenda.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_HistoricoCompraVenda.setText("Histórico Venda/Compra");
        jButton_HistoricoCompraVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_HistoricoCompraVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton_Contact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Estoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_VendaCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Despesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_HistoricoCompraVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_VendaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Despesas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_HistoricoCompraVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(437, 437, 437))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Contact, jButton_Despesas, jButton_Estoque, jButton_HistoricoCompraVenda, jButton_VendaCompra});

        pack();
    }

    // Shows a message on screen with a given string
    public void showMessage(String info)
    {
        JOptionPane.showMessageDialog(this, info,"Atenção" ,JOptionPane.INFORMATION_MESSAGE);
        log.info(info);
    }
    
    // Opens Expense's form
    private void jButton_DespesasActionPerformed(java.awt.event.ActionEvent evt)
    {
        new ExpenseView().setVisible(true);
        log.debug("Open ExpenseView");
    }

    // Opens Stock's form
    private void jButton_EstoqueActionPerformed(java.awt.event.ActionEvent evt)
    {
       new StockView().setVisible(true);
       log.debug("Open StockView");
    }

    // Opens Contact's form
    private void jButton_ContatosActionPerformed(java.awt.event.ActionEvent evt)
    {
        SalePurchaseView.purchaseSaleMode = false;
        new ContactView().setVisible(true);
        log.debug("Open ContactView");
    }
    
    // Opens SalePurchase's form
    private void jButton_VendaCompraActionPerformed(java.awt.event.ActionEvent evt)
    {
        new SalePurchaseView().setVisible(true);
        log.debug("Open SalePurchaseView");
    }

    // Opens SalePurchaseHistoric's form
    private void jButton_HistoricoCompraVendaActionPerformed(java.awt.event.ActionEvent evt)
    {
        new SalePurchaseHistoricView().setVisible(true);
        log.debug("Open SalePurchaseHistoricView");
    }
    
    // Main function of EnterpriseManagement
    public static void main(String args[])
    {
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            log.error("ClassNotFoundException", ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            log.error("InstantiationException", ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            log.error("IllegalAccessException", ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(EnterpriseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            log.error("UnsupportedLookAndFeelException", ex);
        }
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new EnterpriseManagement().setVisible(true);
                log.debug("Open EnterpriseManagement");
            }
        });
    }
           
}
