package view;

import controller.ControleTransacao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Compra;
import model.Fornecedor;
import model.Funcionario;
import model.Produto;
import model.Transacao;
import model.Venda;

public class GestaoEmpresa extends javax.swing.JFrame
{
    
    Cliente umCliente;
    Funcionario umFuncionario;
    Fornecedor umFornecedor;
    Produto umProduto;
    ArrayList<Produto> listaProduto;

    // Constructor of the EnterpriseManagement's class
    public GestaoEmpresa()
    {
        initComponents();
        umProduto = new Produto("Produto", null, 10.0, WIDTH);
        listaProduto = new ArrayList<Produto>();
        listaProduto.add(umProduto);
        umCliente = new Cliente("Cliente", null, null, null);
        umFuncionario = new Funcionario("Funcionario", null, null, null, null, null, WIDTH, null);
        umFornecedor = new Fornecedor("Fornecedor", null, null, null, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Contatos = new javax.swing.JButton();
        jButton_Estoque = new javax.swing.JButton();
        jButton_VendaCompra = new javax.swing.JButton();
        jButton_Despesas = new javax.swing.JButton();
        jButton_HistoricoCompraVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 800));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Gestão Empresa - 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton_Contatos.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_Contatos.setText("Contatos");
        jButton_Contatos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_ContatosActionPerformed(evt);
            }
        });

        jButton_Estoque.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_Estoque.setText("Estoque");
        jButton_Estoque.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_EstoqueActionPerformed(evt);
            }
        });

        jButton_VendaCompra.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_VendaCompra.setText("Venda/Compra");
        jButton_VendaCompra.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_VendaCompraActionPerformed(evt);
            }
        });

        jButton_Despesas.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_Despesas.setText("Despesas");
        jButton_Despesas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_DespesasActionPerformed(evt);
            }
        });

        jButton_HistoricoCompraVenda.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton_HistoricoCompraVenda.setText("Histórico Venda/Compra");
        jButton_HistoricoCompraVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_HistoricoCompraVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton_Contatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Estoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_VendaCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Despesas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_HistoricoCompraVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Contatos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_VendaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Despesas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_HistoricoCompraVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(437, 437, 437))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Contatos, jButton_Despesas, jButton_Estoque, jButton_HistoricoCompraVenda, jButton_VendaCompra});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Shows a message on screen with a given string
    public void exibirInformacao(String info)
    {
        JOptionPane.showMessageDialog(this, info,"Atenção" ,JOptionPane.INFORMATION_MESSAGE);
    }
    
    // Opens Despesas' form
    private void jButton_DespesasActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jButton_DespesasActionPerformed
        new TelaDespesas().setVisible(true);
    }//GEN-LAST:event_jButton_DespesasActionPerformed

    // Opens Estoque's form
    private void jButton_EstoqueActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jButton_EstoqueActionPerformed
       new TelaEstoque().setVisible(true);
    }//GEN-LAST:event_jButton_EstoqueActionPerformed

    // Opens Contatos' form
    private void jButton_ContatosActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jButton_ContatosActionPerformed
        TelaVendaCompra.modoVendaCompra=false;
        new ContactView().setVisible(true);
    }//GEN-LAST:event_jButton_ContatosActionPerformed

    // Opens VendaCompra's form
    private void jButton_VendaCompraActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jButton_VendaCompraActionPerformed
        new TelaVendaCompra().setVisible(true);
    }//GEN-LAST:event_jButton_VendaCompraActionPerformed

    // Opens HistoricoVendaCompra's form
    private void jButton_HistoricoCompraVendaActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jButton_HistoricoCompraVendaActionPerformed
        new TelaHistoricoVendaCompra().setVisible(true);
    }//GEN-LAST:event_jButton_HistoricoCompraVendaActionPerformed

    // Main function of EnterpriseManagement
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GestaoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GestaoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GestaoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GestaoEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GestaoEmpresa().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Contatos;
    private javax.swing.JButton jButton_Despesas;
    private javax.swing.JButton jButton_Estoque;
    private javax.swing.JButton jButton_HistoricoCompraVenda;
    private javax.swing.JButton jButton_VendaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
