/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import static view.TelaDadosProdutos.umControleEstoque;
import static view.TelaVendaCompra.modoProduto;
import static view.TelaVendaCompra.modoVendaCompra;


/**
 *
 * @author Ricardo
 */
public class TelaEstoque extends javax.swing.JFrame {

    GestaoEmpresa principal;
    static boolean novoProduto = true;
    static String codigoTabela;
    static String descricaoTabela;
    static boolean returnProduto=false;
    
    public TelaEstoque() {
        initComponents();
        jButton_EditarProduto.setEnabled(false);
        jButton_ExcluirProduto.setEnabled(false);
        jButton_ConfirmarProduto.setVisible(false);
        jButton_ConfirmarProduto.setEnabled(false);
        if(TelaVendaCompra.modoProduto==true)
            jButton_ConfirmarProduto.setVisible(novoProduto);
        if(modoVendaCompra==true)
            jButton_AdicionarProduto.setEnabled(false);
        if(TelaDadosProdutos.infoCarregar==true)
            carregarLista();
        TelaDadosProdutos.infoCarregar=false;
        carregarLista();
        jTextField_NomeProduto.requestFocus();
    }

    public void exibirInformacao(String info)
    {
        JOptionPane.showMessageDialog(this, info,"Atenção" ,JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void carregarLista()
    {
        DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();  //Funçao para limpar a tabela
        model1.setRowCount(0);
        jTable2.setModel(model1);
        
        ArrayList<Produto> listaProdutos = umControleEstoque.getListaProdutos();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        for (Produto p : listaProdutos) {
            model.addRow(new String[]{p.getCodigo(),p.getDescricao(),Double.toString(p.getPrecoCompra()),Double.toString(p.getPrecoVenda()),Double.toString( p.getQuantidade()) });     
        }
        jTable2.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_NomeProduto = new javax.swing.JTextField();
        jButton_PesquisarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_AdicionarProduto = new javax.swing.JButton();
        jButton_EditarProduto = new javax.swing.JButton();
        jButton_ExcluirProduto = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_ConfirmarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setBounds(new java.awt.Rectangle(450, 300, 0, 0));

        jButton_PesquisarProduto.setText("Pesquisar");
        jButton_PesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PesquisarProdutoActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel
            (
                null,
                new String [] {
                    "Código", "Descrição","Preço Compra","Preço Venda", "Quantidade"
                }
            )
            {
                @Override
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                    return false;
                }
            });
            jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable2MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTable2);

            jButton_AdicionarProduto.setText("Adicionar Produto");
            jButton_AdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_AdicionarProdutoActionPerformed(evt);
                }
            });

            jButton_EditarProduto.setText("Editar");
            jButton_EditarProduto.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_EditarProdutoActionPerformed(evt);
                }
            });

            jButton_ExcluirProduto.setText("Excluir");
            jButton_ExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_ExcluirProdutoActionPerformed(evt);
                }
            });

            jButton_Cancelar.setText("Sair");
            jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_CancelarActionPerformed(evt);
                }
            });

            jButton_ConfirmarProduto.setText("Confirmar");
            jButton_ConfirmarProduto.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_ConfirmarProdutoActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
            jLabel1.setText("Cadastro de Produto");

            jLabel2.setText("Pesquisar Produto pelo Código ou Descrição:");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_Cancelar)
                                    .addGap(65, 65, 65)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextField_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_PesquisarProduto)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jButton_ConfirmarProduto)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton_AdicionarProduto)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_ExcluirProduto)
                                        .addComponent(jButton_EditarProduto))))
                            .addGap(0, 0, Short.MAX_VALUE))))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton_Cancelar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel1)))
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_PesquisarProduto))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_AdicionarProduto)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_EditarProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_ExcluirProduto)
                            .addGap(33, 33, 33)))
                    .addComponent(jButton_ConfirmarProduto))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton_PesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PesquisarProdutoActionPerformed
        if("".equals(jTextField_NomeProduto.getText()))
        {
            carregarLista();
            if(jTable2.getRowCount()==0)
                exibirInformacao("Nenhum produto fora cadastrado até o momento.");          
        }
        else
        {
            Produto outroProduto = umControleEstoque.pesquisarProduto(jTextField_NomeProduto.getText(),true);
            DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();  //Funçao para limpar a tabela
            model1.setRowCount(0);
            jTable2.setModel(model1);
            
            ArrayList<Produto> listaTeste = umControleEstoque.getListaProdutos();
            
            if(listaTeste.size() == 0)
            {
                exibirInformacao("Nenhum produto fora cadastrado até o momento."); 
            }
                    
            else if(outroProduto==null)
                exibirInformacao("Produto não encontrado!");
            else
            {
                model1.addRow(new String[]{outroProduto.getCodigo(),outroProduto.getDescricao(),Double.toString(outroProduto.getPrecoCompra()),Double.toString(outroProduto.getPrecoVenda()),Double.toString(outroProduto.getQuantidade())});
                jTextField_NomeProduto.setText(outroProduto.getCodigo());
            }
        }
    }//GEN-LAST:event_jButton_PesquisarProdutoActionPerformed

    private void jButton_AdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdicionarProdutoActionPerformed
        new TelaDadosProdutos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AdicionarProdutoActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        this.dispose();
        if(modoProduto==true)
            new TelaVendaCompra().setVisible(true);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_EditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarProdutoActionPerformed
        novoProduto=false;
        new TelaDadosProdutos().setVisible(true);
    }//GEN-LAST:event_jButton_EditarProdutoActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        codigoTabela = (String) model.getValueAt(jTable2.getSelectedRow(), 0);
        descricaoTabela = (String) model.getValueAt(jTable2.getSelectedRow(), 1);
        jButton_EditarProduto.setEnabled(true);
        jButton_ExcluirProduto.setEnabled(true);
        jButton_ConfirmarProduto.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton_ExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirProdutoActionPerformed
        umControleEstoque.removerProduto(umControleEstoque.pesquisarProduto(codigoTabela,false));
        carregarLista();
        jButton_EditarProduto.setEnabled(false);
        jButton_ExcluirProduto.setEnabled(false);
    }//GEN-LAST:event_jButton_ExcluirProdutoActionPerformed

    private void jButton_ConfirmarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarProdutoActionPerformed
        returnProduto=true;
        modoProduto=false;
        this.dispose();
        new TelaVendaCompra().setVisible(true);
    }//GEN-LAST:event_jButton_ConfirmarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AdicionarProduto;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_ConfirmarProduto;
    private javax.swing.JButton jButton_EditarProduto;
    private javax.swing.JButton jButton_ExcluirProduto;
    private javax.swing.JButton jButton_PesquisarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_NomeProduto;
    // End of variables declaration//GEN-END:variables
}
