/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControleEstoque;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Produto;
import static view.TelaEstoque.novoProduto;

public class TelaDadosProdutos extends javax.swing.JFrame
{
    Produto umProduto;
    static ControleEstoque umControleEstoque = new ControleEstoque();
    Produto editProduto;
    TelaEstoque telaEstoque;
    static boolean infoCarregar=false;
    
    public TelaDadosProdutos()
    {
        initComponents();
        preencherCampos();
        jTextField_QuantidadeProduto.setEnabled(false);
        preencherCodigo();
        jTextField_DescricaoProduto.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_NomeProduto = new javax.swing.JTextField();
        jTextField_DescricaoProduto = new javax.swing.JTextField();
        jTextField_PrecoCompra = new javax.swing.JTextField();
        jTextField_QuantidadeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_SalvarProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_PrecoVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Produto");
        setBounds(new java.awt.Rectangle(450, 300, 0, 0));

        jButton_Cancelar.setText("Sair");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jTextField_PrecoCompra.setText("0.00");

        jTextField_QuantidadeProduto.setText("0.0");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Preço Venda:");

        jLabel4.setText("Quantidade:");

        jButton_SalvarProduto.setText("Salvar");
        jButton_SalvarProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_SalvarProdutoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Novo Produto");

        jLabel6.setText("R$");

        jLabel7.setText("Preço Compra:");

        jLabel8.setText("R$");

        jTextField_PrecoVenda.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_SalvarProduto)
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_PrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_PrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTextField_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_QuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Cancelar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_NomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_DescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_PrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_PrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_QuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton_SalvarProduto))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void exibirInformacao(String info)
    {
        JOptionPane.showMessageDialog(this, info,"Atenção" ,JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void preencherCodigo()
    {
        if(novoProduto==true)
        {
            ArrayList<Produto> listaTeste = umControleEstoque.getListaProdutos();
            if(listaTeste.isEmpty())
            {
                jTextField_NomeProduto.setText("1");
            }
            
            else
            {
                jTextField_NomeProduto.setText(Integer.toString
                                            (Integer.parseInt
                                            (listaTeste.get
                                            (listaTeste.size()-1)
                                            .getCodigo())
                                             +1));
            }
        }
    }
    
    private void preencherCampos()
    {
        if(novoProduto==false)
        {
	        editProduto = umControleEstoque.pesquisarProduto(TelaEstoque.codigoTabela,false);
	        jTextField_NomeProduto.setText(editProduto.getCodigo());
	        jTextField_DescricaoProduto.setText(editProduto.getDescricao());
	        jTextField_PrecoCompra.setText(Double.toString(editProduto.getPrecoCompra()));
	        jTextField_PrecoVenda.setText(Double.toString(editProduto.getPrecoVenda()));
	        jTextField_QuantidadeProduto.setText(Double.toString(editProduto.getQuantidade()));
        }
    }
    
    private void limparCampos()
    {
        jTextField_NomeProduto.setText("");
        jTextField_DescricaoProduto.setText("");
        jTextField_PrecoCompra.setText("0.00");
        jTextField_PrecoVenda.setText("0.00");
        jTextField_QuantidadeProduto.setText("0.0");
    }
    
    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jButton_CancelarActionPerformed
        if(!jTextField_DescricaoProduto.getText().equals(""))
        {
            exibirInformacao("Produto não adicionado");
        }
            
        new TelaEstoque().setVisible(true);
        this.dispose();
        infoCarregar=true;
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jButton_SalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarProdutoActionPerformed
        if(!jTextField_NomeProduto.getText().equals("")&&!jTextField_DescricaoProduto.getText().equals("")&&!jTextField_PrecoCompra.getText().equals(""))
        {
            String codigo = jTextField_NomeProduto.getText();
            String descricao = jTextField_DescricaoProduto.getText();
            double precoCompra = Double.parseDouble(jTextField_PrecoCompra.getText());
            double precoVenda = Double.parseDouble(jTextField_PrecoVenda.getText());
            double estoque = Double.parseDouble(jTextField_QuantidadeProduto.getText());

            if(TelaEstoque.novoProduto==true)
            {
                umProduto = new Produto(codigo, descricao, precoCompra, estoque, precoVenda);
                
                if(umControleEstoque.pesquisarProduto(umProduto.getCodigo(),false)==null
                        &&umControleEstoque.pesquisarProduto(umProduto.getDescricao(),false)==null)
                {
                    umControleEstoque.adicionarProduto(umProduto);
                    exibirInformacao("Produto Adicionado!");
                }
                
                else if(umControleEstoque.pesquisarProduto(umProduto.getCodigo(),false)!=null)
                {
                    exibirInformacao("Produto com esse código já existente no estoque!");
                }
                
                else if(umControleEstoque.pesquisarProduto(umProduto.getDescricao(),false)!=null)
                {
                    exibirInformacao("Produto com essa Descrição já existente no estoque!");
                }
            }
            
            else if(TelaEstoque.novoProduto==false)
            {    
                if(!editProduto.getCodigo().equals(jTextField_NomeProduto.getText()))
                {
                    exibirInformacao("Não é permitido a alteração do código do produto!");
                }
                
                else{
                    editProduto.setCodigo(codigo);
                    editProduto.setDescricao(descricao);
                    editProduto.setPreco(precoCompra);
                    editProduto.setPreco(precoVenda);
                    editProduto.setQuantidade(estoque);   
                    exibirInformacao("Produto Editado!");
                }
            }
            
            limparCampos();
            preencherCodigo();
            novoProduto=true;
        }
        
        else if(jTextField_NomeProduto.getText().equals(""))
        {
            exibirInformacao("Digite um código para o produto");
            jTextField_NomeProduto.requestFocus();
        }
        
        else if(jTextField_DescricaoProduto.getText().equals(""))
        {
            exibirInformacao("Digite uma descrição para o produto");
            jTextField_DescricaoProduto.requestFocus();
        }
        
        else if(jTextField_PrecoCompra.getText().equals(""))
        {
            exibirInformacao("Digite um preço de compra para o produto");
            jTextField_PrecoCompra.requestFocus();
        }
        
        else if(jTextField_PrecoVenda.getText().equals(""))
        {
            exibirInformacao("Digite um preço de venda para o produto");
            jTextField_PrecoCompra.requestFocus();
        }
    }//GEN-LAST:event_jButton_SalvarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TelaDadosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TelaDadosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TelaDadosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TelaDadosProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TelaDadosProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_SalvarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_DescricaoProduto;
    private javax.swing.JTextField jTextField_NomeProduto;
    private javax.swing.JTextField jTextField_PrecoCompra;
    private javax.swing.JTextField jTextField_PrecoVenda;
    private javax.swing.JTextField jTextField_QuantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
